ci:
    autofix_commit_msg: |
        ci(pre-commit.ci): auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_commit_msg: 'ci(pre-commit.ci): pre-commit autoupdate'
    autoupdate_schedule: weekly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black", "-l", "88"]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: ["--ignore", "F722,F821,E203,W503,F405", "--max-line-length", "88","--max-complexity","5"]
      # These files are not supported by BlenderNC development, and exclude tests.
      exclude: |
        (?x)(
            ^blendernc/addon_updater.*py|
            ^tests/.*py
        )
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
    - id: commitlint
      stages: [commit-msg]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.21.2
    hooks:
    - id: commitizen
      stages: [commit-msg]